
  chrome.storage.local.get("userPublicId", (result) => {
    if (!result.userPublicId) {
      chrome.storage.local.set({ userPublicId: "autoGeneratedValue" }, () => {   
      });
    }
  });

  const s = document.createElement('script');
  s.src = chrome.runtime.getURL('bridge.js');
  (document.head||document.documentElement).appendChild(s);
  s.onload = () => s.remove();


  window.addEventListener("message", (event) => {
    if (event.source === window && event.data?.type === "SET_USER_PUBLIC_ID") {
        chrome.storage.local.set({ userPublicId: event.data.value }, () => {
            console.log("userPublicId saved in extension:", event.data.value);
        });
    }

    if (event.data?.type === "GET_USER_PUBLIC_ID") {
        chrome.storage.local.get("userPublicId", (res) => {
          window.postMessage({ type: "FROM_EXTENSION", data: res.userPublicId || null }, "*");
        });
    }
  });

